<div class="event-info-wrap">
	<h2 class="h2-headline border-bottom">UP COMING EVENT</h2>
	<ul class="event-info-list">
	    <li class=close>
            <a href="/event/think-002.html#think-050">
                <dl class="event-info-side-column">
                    <dt><!--<span class="icon-new">NEW</span>--><time datetime="2018-12-08">2018/12/08</time></dt>
                    <dd>Junktion.2018</dd>
                </dl>
            </a>
        </li>
	    <li class="close">
            <a href="/event/think-002.html#think-049">
                <dl class="event-info-side-column">
                    <dt><time datetime="2018-09-07">2018/11/22</time></dt>
                    <dd>SADAR BAHAR in KOBE</dd>
                </dl>
            </a>
        </li>
	    <li class="close">
            <a href="/event/think-002.html#think-048">
                <dl class="event-info-side-column">
                    <dt><time datetime="2018-09-07">2018/09/07</time></dt>
                    <dd>EMMA HOUSE</dd>
                </dl>
            </a>
        </li>
	    <li class="close">
            <a href="/event/think-002.html#think-047">
                <dl class="event-info-side-column">
                    <dt><time datetime="2018-06-30">2018/06/30</time></dt>
                    <dd>S&S IWAKI</dd>
                </dl>
            </a>
        </li>
        <li class="close">
            <a href="/event/think-002.html#think-045">
                <dl class="event-info-side-column">
                    <dt><time datetime="2018-06-24">2018/06/24</time></dt>
                    <dd>90BPM TAKEOVER FREE THE ROBOTS -JAPAN TOUR FINAL-</dd>
                </dl>
            </a>
        </li>
	    <li class="close">
            <a href="/event/think-002.html#think-044">
                <dl class="event-info-side-column">
                    <dt><time datetime="2018-04-15">2018/04/15</time></dt>
                    <dd>JAM JACK CAFE 2018</dd>
                </dl>
            </a>
        </li>
	    <li class="close">
            <a href="/event/think-002.html#think-042">
                <dl class="event-info-side-column">
                    <dt><time datetime="2018-02-16">2018/02/16</time></dt>
                    <dd>Bad Moondog Rizing!!! part II</dd>
                </dl>
            </a>
        </li>
		<li class="close">
			<a href="/event/think-002.html#think-041">
				<dl class="event-info-side-column">
					<dt><!--<span class="icon-new">NEW</span>--><time datetime="2017-11-26">2017/11/26</time></dt>
					<dd>SOCiAL FUNK! 2017</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-040">
				<dl class="event-info-side-column">
					<dt><time datetime="2017-10-03">2017/10/03</time></dt>
					<dd>OUTPUT</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-039">
				<dl class="event-info-side-column">
					<dt><time datetime="2017-07-13">2017/07/13</time></dt>
					<dd>宇宙平和音楽祭</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-038">
				<dl class="event-info-side-column">
					<dt><time datetime="2017-06-15">2017/06/15</time></dt>
					<dd>Down Beat Session</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-037">
				<dl class="event-info-side-column">
					<dt><time datetime="2017-05-27">2017/05/27,28</time></dt>
					<dd>「東京オリンピックを目指せ！」エクストリームスポーツ華麗な技の競演</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-036">
				<dl class="event-info-side-column">
					<dt><time datetime="2017-05-27">2017/05/27</time></dt>
					<dd>DJ KRUSH - NEW ALBUM 「軌跡」 RELEASE PARTY</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-035">
				<dl class="event-info-side-column">
					<dt><time datetime="2017-05-04">2017/05/04</time></dt>
					<dd>HARLEM 20th ANNIVERSARY GOLDEN 4DAYS</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-034">
				<dl class="event-info-side-column">
					<dt><time datetime="2017-04-20">2017/04/20</time></dt>
					<dd>Down Beat Session</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-033">
				<dl class="event-info-side-column">
					<dt><time datetime="2017-03-04">2017/03/04</time></dt>
					<dd>RELAX</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-032">
				<dl class="event-info-side-column">
					<dt><time datetime="2017-02-19">2017/02/19</time></dt>
					<dd>MARDIGRAS 2nd Anniversary</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-031">
				<dl class="event-info-side-column">
					<dt><time datetime="2017-02-18">2017/02/18</time></dt>
					<dd>SOULPOT RECORDS Presents “No.079″</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-030">
				<dl class="event-info-side-column">
					<dt><time datetime="2017-02-16">2017/02/16</time></dt>
					<dd>Down Beat Session</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-029">
				<dl class="event-info-side-column">
					<dt><time datetime="2017-01-07">2017/01/07</time></dt>
					<dd>90BPM TAKEOVER</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-028">
				<dl class="event-info-side-column">
					<dt><time datetime="2016-12-31">2016/12/31</time></dt>
					<dd>Solfa 2016-2017 Countdown Party</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-027">
				<dl class="event-info-side-column">
					<dt><time datetime="2016-12-15">2016/12/15</time></dt>
					<dd>Down Beat Session</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-026">
				<dl class="event-info-side-column">
					<dt><time datetime="2016-12-08">2016/12/08</time></dt>
					<dd>FAVS #6</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-025">
				<dl class="event-info-side-column">
					<dt><time datetime="2016-12-08">2016/11/05</time></dt>
					<dd>Laboratory</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-024">
				<dl class="event-info-side-column">
					<dt><time datetime="2016-10-20">2016/10/20</time></dt>
					<dd>Down Beat Session</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-023">
				<dl class="event-info-side-column">
					<dt><time datetime="2016-10-09">2016/10/09</time></dt>
					<dd>MARDIGRAS THE LIVE!!</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-022">
				<dl class="event-info-side-column">
					<dt><time datetime="2016-09-07">2016/09/07</time></dt>
					<dd>Super Plume x 90BPM TAKEOVER</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-021">
				<dl class="event-info-side-column">
					<dt><time datetime="2016-08-20">2016/08/20</time></dt>
					<dd>SUIQA BAR</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-020">
				<dl class="event-info-side-column">
					<dt><time datetime="2016-07-24">2016/07/24</time></dt>
					<dd>THE DREAM SCENE</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-019">
				<dl class="event-info-side-column">
					<dt><time datetime="2016-05-13">2016/05/13</time></dt>
					<dd>A-1 LOUNGE</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-018">
				<dl class="event-info-side-column">
					<dt><time datetime="2016-05-07">2016/05/07</time></dt>
					<dd>THIRD CULTURE vol.28/7 SEVEN</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-017">
				<dl class="event-info-side-column">
					<dt><time datetime="2016-05-02">2016/05/02</time></dt>
					<dd>NEIGHBOR</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-016">
				<dl class="event-info-side-column">
					<dt><time datetime="2016-03-26">2016/03/26</time></dt>
					<dd>BANANAS!!</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-015">
				<dl class="event-info-side-column">
					<dt><time datetime="2015-12-24">2015/12/24</time></dt>
					<dd>Obey Radio Tokyo - James Brown Tribute -</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-014">
				<dl class="event-info-side-column">
					<dt><time datetime="2015-12-24">2015/12/19</time></dt>
					<dd>PAYBACK vol.152</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-013">
				<dl class="event-info-side-column">
					<dt><time datetime="2015-11-29">2015/11/29</time></dt>
					<dd>THE STORE</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-012">
				<dl class="event-info-side-column">
					<dt><time datetime="2015-11-27">2015/11/27</time></dt>
					<dd>Backyard Kitchen vol.7</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-011">
				<dl class="event-info-side-column">
					<dt><time datetime="2015-10-19">2015/10/19</time></dt>
					<dd>Down Beat Session</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-010">
				<dl class="event-info-side-column">
					<dt><time datetime="2015-10-10">2015/10/10</time></dt>
					<dd>THIRD CULTURE vol.25</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-009">
				<dl class="event-info-side-column">
					<dt><time datetime="2015-10-09">2015/10/09</time></dt>
					<dd>DADDY G JAPAN TOUR 2015</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-008">
				<dl class="event-info-side-column">
					<dt><time datetime="2015-09-04">2015/09/04</time></dt>
					<dd>TodaysArt.JP 2015 TOKYO Launching Party</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-007">
				<dl class="event-info-side-column">
					<dt><time datetime="2015-08-30">2015/08/30</time></dt>
					<dd>POTATO SKATE RAMP 2ND ANNIVERSARY</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-006">
				<dl class="event-info-side-column">
					<dt><time datetime="2015-04-18">2015/04/18</time></dt>
					<dd>The Legends of New York Photo Exhibition</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-005">
				<dl class="event-info-side-column">
					<dt><!-- <span class="icon-new">NEW</span> --><time datetime="2014-11-22">2014/11/22</time></dt>
					<dd>TodaysArt JAPAN</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-004">
				<dl class="event-info-side-column">
					<dt><time datetime="2014-11-01">2014/11/01</time></dt>
					<dd>Live Paint DOJO 2014 EXTRA</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-003">
				<dl class="event-info-side-column">
					<dt><time datetime="2014-08-16">2014/08/16</time></dt>
					<dd>BUGPARTY 7th ANNIVERSARY</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-002">
				<dl class="event-info-side-column">
					<dt><time datetime="2014-08-15">2014/08/15</time></dt>
					<dd>HARMONY 外伝</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-002.html#think-001">
				<dl class="event-info-side-column">
					<dt><time datetime="2014-08-09">2014/08/09</time></dt>
					<dd>Heavysick ZERO 12th Anniversary Session</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-001.html#think-010">
				<dl class="event-info-side-column">
					<dt><time datetime="2014-08-08">2014/08/08</time></dt>
					<dd>Triple 3 Release Party</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-001.html#think-008">
				<dl class="event-info-side-column">
					<dt><time datetime="2014-07-05">2014/07/05</time></dt>
					<dd>Thanks for METRO 24th Anniversary</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-001.html#think-008-a">
				<dl class="event-info-side-column">
					<dt><time datetime="2014-07-01">2014/07/01</time></dt>
					<dd>茶澤音學館</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-001.html#think-007">
				<dl class="event-info-side-column">
					<dt><time datetime="2014-06-27">2014/06/27</time></dt>
					<dd>DJ DUCT "SOME LIKE THAT" 47/47 TOUR in HIROSHIMA</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-001.html#think-006">
				<dl class="event-info-side-column">
					<dt><time datetime="2014-06-14">2014/06/14</time></dt>
					<dd>DJ DUCT "SOME LIKE THAT" 47/47 TOUR in SHIZUOKA</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-001.html#think-005">
				<dl class="event-info-side-column">
					<dt><time datetime="2014-05-22">2014/05/22</time></dt>
					<dd>TWO SNAKES TOUR FREE THE ROBOTS & LEFTO</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-001.html#think-004">
				<dl class="event-info-side-column">
					<dt><time datetime="2014-05-04">2014/05/04</time></dt>
					<dd>DJ DUCT “SOME LIKE THAT” 47/47 TOUR in OKAZAKI</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-001.html#think-003">
				<dl class="event-info-side-column">
					<dt><time datetime="2014-05-03">2014/05/03</time></dt>
					<dd>DJ DUCT “SOME LIKE THAT” 47/47 TOUR in GIFU</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-001.html#think-002">
				<dl class="event-info-side-column">
					<dt><time datetime="2014-05-02">2014/05/02</time></dt>
					<dd>untitled meets DJ DUCT “SOME LIKE THAT” 47/47 Tour</dd>
				</dl>
			</a>
		</li>
		<li class="close">
			<a href="/event/think-001.html#think-001">
				<dl class="event-info-side-column">
					<dt><time datetime="2014-03-21">2014/03/21</time></dt>
					<dd>MEIRO VOL.20 10TH ANNIVERSARY</dd>
				</dl>
			</a>
		</li>
	</ul>
</div>