<div class="news-list-wrap">
	<h2 class="h2-headline border-bottom">NEWS</h2>
	<ul class="news-list">
		<li>
			<a href="/article/2016/jan/think-01.html">
				<dl class="news-info">
					<dt><!-- <span class="icon-new">NEW</span> --><time datetime="2016-02-11">2016/02/11</time></dt>
					<dd>【New Releases】BACKYARD 45</dd>
				</dl>
			</a>
		</li>
		<li>
			<a href="/article/2015/dec/think-01.html">
				<dl class="news-info">
					<dt><time datetime="2015-12-13">2015/12/13</time></dt>
					<dd>BACKYARD 45 MIX.!!!</dd>
				</dl>
			</a>
		</li>
		<li>
			<a href="/article/2015/aug/think-02.html">
				<dl class="news-info">
					<dt><time datetime="2015-08-23">2015/08/23</time></dt>
					<dd>DJ DUCT 新作エディット45リリース決定！</dd>
				</dl>
			</a>
		</li>
		<li>
			<a href="/article/2015/aug/think-01.html">
				<dl class="news-info">
					<dt><time datetime="2015-08-02">2015/08/02</time></dt>
					<dd>TodaysArt.JP 2015 TOKYO Launching Partyに、DJ DUCT出演決定！</dd>
				</dl>
			</a>
		</li>
		<li>
			<a href="/article/2015/mar/think-02.html">
				<dl class="news-info">
					<dt><time datetime="2015-03-17">2015/03/17</time></dt>
					<dd>THE CHEEBA MEGAMIX</dd>
				</dl>
			</a>
		</li>
		<li>
			<a href="/article/2015/mar/think-01.html">
				<dl class="news-info">
					<dt><time datetime="2015-03-15">2015/03/15</time></dt>
					<dd>The Cheebacabra - Retouched (2LP)</dd>
				</dl>
			</a>
		</li>
		<li>
			<a href="/article/2015/feb/think-01.html">
				<dl class="news-info">
					<dt><time datetime="2015-02-02">2015/02/02</time></dt>
					<dd>ten thousand things mix - FEB.2015!!!</dd>
				</dl>
			</a>
		</li>
		<li>
			<a href="/article/2015/jan/think-01.html">
				<dl class="news-info">
					<dt><time datetime="2015-01-07">2015/01/07</time></dt>
					<dd>DJ DUCT MONTHLY MIX - JAN.2015!!!</dd>
				</dl>
			</a>
		</li>
		<li>
			<a href="/article/2014/dec/think-07.html">
				<dl class="news-info">
					<dt><time datetime="2014-12-20">2014/12/20</time></dt>
					<dd>DJ DUCT MONTHLY MIX - DEC.2014!!!</dd>
				</dl>
			</a>
		</li>
		<li>
			<a href="/article/2014/sep/think-06.html">
				<dl class="news-info">
					<dt><time datetime="2014-09-17">2014/09/17</time></dt>
					<dd>One Turntable Funk 45 Mix. (30min)</dd>
				</dl>
			</a>
		</li>
		<li>
			<a href="/article/2014/aug/think-01.html">
				<dl class="news-info">
					<dt><time datetime="2014-08-01">2014/08/01</time></dt>
					<dd>Backyard Garden Party Mix.2 (60min)</dd>
				</dl>
			</a>
		</li>
		<li>
			<a href="http://www.sounddesigner.jp/SDRZ/index2014summer.shtml" target=”_blank”>
				<dl class="news-info">
					<dt><time datetime="2014-07-31">2014/07/31</time></dt>
					<dd>DJ DUCT インタビュー掲載誌発売</dd>
				</dl>
			</a>
		</li>
		<li>
			<a href="/47Tour.html">
				<dl class="news-info">
					<dt><time datetime="2014-05-28">2014/05/28</time></dt>
					<dd>SOME LIKE THAT 47/47 TOUR Schedule</dd>
				</dl>
			</a>
		</li>
		<li>
			<a href="/47Tour.html">
				<dl class="news-info">
					<dt><time datetime="2014-05-28">2014/05/28</time></dt>
					<dd>SOME LIKE THAT 47/47 TOUR Schedule</dd>
				</dl>
			</a>
		</li>
		<li>
			<a href="/article/2014/jan/think-05.html">
				<dl class="news-info">
					<dt><time datetime="2014-02-05">2014/02/05</time></dt>
					<dd>DJ DUCT SOME LIKE THAT Release</dd>
				</dl>
			</a>
		</li>
	</ul>
</div>